version: "2"
services:
  app:
    image: nicbet/phoenix:1.7.12
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./:/app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
