services:
  app:
    build:
      context: .
      dockerfile: ./dockerfile
    depends_on:
      - db
    ports:
      - "4000:4000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_DB=timeman-dev
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
